bash: python3.8: command not found
